-- Question bank. Generated by sql/build_db.py from content/*.json.
-- Never edit the resulting database by hand: the next build overwrites it.

PRAGMA foreign_keys = ON;

CREATE TABLE Domains (
    DomainID INTEGER PRIMARY KEY,
    Title    TEXT NOT NULL,
    Weight   REAL NOT NULL
);

CREATE TABLE Questions (
    QuestionID   INTEGER PRIMARY KEY,
    Slug         TEXT    NOT NULL UNIQUE,
    QuestionText TEXT    NOT NULL UNIQUE,
    DomainID     INTEGER NOT NULL REFERENCES Domains(DomainID),
    Subdomain    TEXT    NOT NULL,
    Difficulty   INTEGER NOT NULL CHECK (Difficulty BETWEEN 1 AND 3),
    Explanation  TEXT    NOT NULL,
    Reference    TEXT
);

CREATE INDEX idx_questions_domain ON Questions(DomainID);

CREATE TABLE Answers (
    AnswerID   INTEGER PRIMARY KEY,
    QuestionID INTEGER NOT NULL REFERENCES Questions(QuestionID) ON DELETE CASCADE,
    AnswerText TEXT    NOT NULL,
    IsCorrect  INTEGER NOT NULL CHECK (IsCorrect IN (0, 1))
);

CREATE INDEX idx_answers_question ON Answers(QuestionID);
