name: This a workflow title
on: [push]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  TOKEN_BOT: ${{secrets.TOKEN_BOT}}
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment Variable from GitHub Secrets
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: echo "BOT_TOKEN=$BOT_TOKEN" >> $GITHUB_ENV
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Tag as "latest" and Push
      run: |
        docker tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }} $DOCKER_USER/$REPO_NAME:latest
        docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
        docker push $DOCKER_USER/$REPO_NAME:latest
